services:
  app:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    container_name: shopify-starter-app
    env_file:
      - ./apps/server/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
    volumes:
      - ./:/app:cached
    #      - /app/node_modules # anonymous volume for node_modules only
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

  postgres:
    container_name: postgres-shopify-starter-app
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: shopify-app
    ports:
      - "5432:5432"
    volumes:
      - shopify-starter-app_db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio-shopify-starter-app
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data

  redis:
    image: redis:latest
    container_name: redis-shopify-starter-app
    restart: unless-stopped
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  minio_storage: {}
  shopify-starter-app_db_data:
  shopify-starter-app_redis_data:
    driver: local
  redis-data: {}
