services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: poker-study-platform-app
    env_file:
      - ./.env
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
    volumes:
      - ./:/app:cached
      - /app/node_modules # anonymous volume for node_modules only
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
