# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "71cbb3bc06d47f5599c7f372418e953f"
name = "amortizable-customer-app"
handle = "amortizable-customer-app-16"
application_url = "https://treefrog-right-kingfish.ngrok-free.app/"
embedded = true

[build]
dev_store_url = "app-starter-node.myshopify.com"

[auth]
redirect_urls = [
    "https://treefrog-right-kingfish.ngrok-free.app/api/v1/shopify-auth/offline",
    "https://treefrog-right-kingfish.ngrok-free.app/api/v1/shopify-app-install/callback",
    "https://treefrog-right-kingfish.ngrok-free.app/api/v1/shopify-auth/online"
]

[webhooks]
api_version = "2024-04"

[[webhooks.subscriptions]]
uri = "https://treefrog-right-kingfish.ngrok-free.app/api/v1/mandatory-webhook/customers/data-request"
compliance_topics = [ "customers/data_request" ]

[[webhooks.subscriptions]]
uri = "https://treefrog-right-kingfish.ngrok-free.app/api/v1/mandatory-webhook/customers/redact"
compliance_topics = [ "customers/redact" ]

[[webhooks.subscriptions]]
uri = "https://treefrog-right-kingfish.ngrok-free.app/api/v1/mandatory-webhook/shops/redact"
compliance_topics = [ "shop/redact" ]

[pos]
embedded = false
