# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9a99b4bb8b3928da62b69f55bbdfa953"
name = "public-app"
handle = "public-app-142"
application_url = "https://uncommon-constantly-weevil.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "public-store3.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,write_discounts"

[auth]
redirect_urls = [
  "https://uncommon-constantly-weevil.ngrok-free.app/api/v1/shopify-auth/offline",
  "https://uncommon-constantly-weevil.ngrok-free.app/api/v1/shopify-auth/online",
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
